# (C) Copyright 2024, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Astarte Device SDK Zephyr"
SPDX-PackageDownloadLocation = "https://github.com/astarte-platform/astarte-device-sdk-zephyr"

[[annotations]]
path = "skipfile.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "samples/astarte_app/interfaces/generated_interfaces.c"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "samples/astarte_app/interfaces/generated_interfaces.h"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "Apache-2.0"
